name: RunsafeServices
load: STARTUP
main: no.runsafe.RunsafeServices
version: 1.1
authors: [mortenn, Kruithne]
depend: []
description: Message Bus Plugin for the Runsafe plugin framework
commands:
  runsafe:
    description: Manage runsafe plugins
    aliases: [rs]

permissions:
  runsafe.config.reload:
    description: Access to reload configuration
    default: false