name: RunsafeServices
load: STARTUP
main: no.runsafe.ServicesPlugin
version: 1.2.@BUILD@
authors: [mortenn, Kruithne]
depend: []
description: Message Bus Plugin for the Runsafe plugin framework
commands:
  runsafe:
    description: Manage runsafe plugins
    aliases: [rs]
  help:
    description: Command usage help

permissions:
  runsafe.config.reload:
    description: Access to reload configuration
    default: false